package com.example.gjj.myapplication.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class UserModel implements Serializable {
    public UserData data;
    public String code;
    public String msg;
    public boolean success;

    public UserData getData() {
        return data;
    }

    public void setData(UserData data) {
        this.data = data;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public boolean isSuccess() {
        return success;
    }

    public void setSuccess(boolean success) {
        this.success = success;
    }

    public class UserData {


        /**
         * 用户ID
         */
        private Long userId;

        /**
         * 上级是用户或店铺（0：用户， 1：店铺）
         */
        private Byte userOrShop;

        /**
         * 用户推荐人或店铺id
         */
        private Long parentUserId;

        /**
         * 登录密码
         */
        private String userPwd;

        /**
         * 用户昵称
         */
        private String nickName;

        /**
         * 头像
         */
        private String logo;

        /**
         * 性别（0：女，1：男）
         */
        private int gender;

        /**
         * 二维码(地址)
         */
        private String userQrcode;

        /**
         * 注册时间
         */
        private Long registerTime;

        /**
         * 支付密码
         */
        private String paypwd;

        /**
         * 是否实名(0:否，1：是)
         */
        private int authentication;

        /**
         * 实名认证申请时间
         */
        private Long authenticateTime;

        /**
         * 创建时间
         */
        private Long createTime;

        /**
         * 是否删除,默认0，1删除
         */
        private Byte cutOff;

        /**
         * 删除时间
         */
        private Long cutOffTime;

        /**
         * 用户等级（0:v0、1:v1、2:v2、3:v3）
         */
        private int userLevel;

        /**
         * 用户来源（备用字段，0：本地会员，1~99：其他第三方平台）
         */
        private Byte userRoot;

        /**
         * 身份证正面
         */
        private String idZ;

        /**
         * 身份证反面
         */
        private String idF;

        /**
         * 身份证号
         */
        private String idNo;

        /**
         * 实名审核通过时间
         */
        private Long checkPassTime;

        /**
         * 实名审核状态(0:审核中，1：审核通过，2：审核不通过)
         */
        private Byte checkStatus;

        /**
         * 审核人id
         */
        private Integer auditorId;

        /**
         * 手机号码
         */
        private Long phone;

        /**
         * 推荐人（上级）身份（0：会员，1：店铺）
         */
        private Byte referrerIdentity;

        /**
         * 真实姓名
         */
        private String realName;

        /**
         * 累计消费总金额(不包含批发)
         */
        private BigDecimal consumeSum;

        /**
         * 累计获得消费券
         */
        private BigDecimal sumConsumTicket;

        /**
         * 是否是v1、v2粉丝数达到3个的v0级会员（0：否  1：是）
         */
        private Byte enoughFansV0;

        /**  */
        private Long fId;

        /**
         * 实名审核不通过原因
         */
        private String checkDetail;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tyg_user_list
         *
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        private static final long serialVersionUID = 1L;

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.user_id
         *
         * @return the value of tyg_user_list.user_id
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Long getUserId() {
            return userId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.user_id
         *
         * @param userId the value for tyg_user_list.user_id
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setUserId(Long userId) {
            this.userId = userId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.user_or_shop
         *
         * @return the value of tyg_user_list.user_or_shop
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Byte getUserOrShop() {
            return userOrShop;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.user_or_shop
         *
         * @param userOrShop the value for tyg_user_list.user_or_shop
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setUserOrShop(Byte userOrShop) {
            this.userOrShop = userOrShop;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.parent_user_id
         *
         * @return the value of tyg_user_list.parent_user_id
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Long getParentUserId() {
            return parentUserId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.parent_user_id
         *
         * @param parentUserId the value for tyg_user_list.parent_user_id
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setParentUserId(Long parentUserId) {
            this.parentUserId = parentUserId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.user_pwd
         *
         * @return the value of tyg_user_list.user_pwd
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public String getUserPwd() {
            return userPwd;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.user_pwd
         *
         * @param userPwd the value for tyg_user_list.user_pwd
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setUserPwd(String userPwd) {
            this.userPwd = userPwd;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.nick_name
         *
         * @return the value of tyg_user_list.nick_name
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public String getNickName() {
            return nickName;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.nick_name
         *
         * @param nickName the value for tyg_user_list.nick_name
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setNickName(String nickName) {
            this.nickName = nickName;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.logo
         *
         * @return the value of tyg_user_list.logo
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public String getLogo() {
            return logo;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.logo
         *
         * @param logo the value for tyg_user_list.logo
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setLogo(String logo) {
            this.logo = logo;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.gender
         *
         * @return the value of tyg_user_list.gender
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public int getGender() {
            return gender;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.gender
         *
         * @param gender the value for tyg_user_list.gender
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setGender(int gender) {
            this.gender = gender;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.user_qrcode
         *
         * @return the value of tyg_user_list.user_qrcode
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public String getUserQrcode() {
            return userQrcode;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.user_qrcode
         *
         * @param userQrcode the value for tyg_user_list.user_qrcode
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setUserQrcode(String userQrcode) {
            this.userQrcode = userQrcode;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.register_time
         *
         * @return the value of tyg_user_list.register_time
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Long getRegisterTime() {
            return registerTime;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.register_time
         *
         * @param registerTime the value for tyg_user_list.register_time
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setRegisterTime(Long registerTime) {
            this.registerTime = registerTime;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.paypwd
         *
         * @return the value of tyg_user_list.paypwd
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public String getPaypwd() {
            return paypwd;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.paypwd
         *
         * @param paypwd the value for tyg_user_list.paypwd
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setPaypwd(String paypwd) {
            this.paypwd = paypwd;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.authentication
         *
         * @return the value of tyg_user_list.authentication
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public int getAuthentication() {
            return authentication;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.authentication
         *
         * @param authentication the value for tyg_user_list.authentication
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setAuthentication(int authentication) {
            this.authentication = authentication;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.authenticate_time
         *
         * @return the value of tyg_user_list.authenticate_time
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Long getAuthenticateTime() {
            return authenticateTime;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.authenticate_time
         *
         * @param authenticateTime the value for tyg_user_list.authenticate_time
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setAuthenticateTime(Long authenticateTime) {
            this.authenticateTime = authenticateTime;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.create_time
         *
         * @return the value of tyg_user_list.create_time
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Long getCreateTime() {
            return createTime;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.create_time
         *
         * @param createTime the value for tyg_user_list.create_time
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setCreateTime(Long createTime) {
            this.createTime = createTime;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.cut_off
         *
         * @return the value of tyg_user_list.cut_off
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Byte getCutOff() {
            return cutOff;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.cut_off
         *
         * @param cutOff the value for tyg_user_list.cut_off
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setCutOff(Byte cutOff) {
            this.cutOff = cutOff;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.cut_off_time
         *
         * @return the value of tyg_user_list.cut_off_time
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Long getCutOffTime() {
            return cutOffTime;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.cut_off_time
         *
         * @param cutOffTime the value for tyg_user_list.cut_off_time
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setCutOffTime(Long cutOffTime) {
            this.cutOffTime = cutOffTime;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.user_level
         *
         * @return the value of tyg_user_list.user_level
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public int getUserLevel() {
            return userLevel;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.user_level
         *
         * @param userLevel the value for tyg_user_list.user_level
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setUserLevel(int userLevel) {
            this.userLevel = userLevel;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.user_root
         *
         * @return the value of tyg_user_list.user_root
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Byte getUserRoot() {
            return userRoot;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.user_root
         *
         * @param userRoot the value for tyg_user_list.user_root
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setUserRoot(Byte userRoot) {
            this.userRoot = userRoot;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.id_z
         *
         * @return the value of tyg_user_list.id_z
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public String getIdZ() {
            return idZ;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.id_z
         *
         * @param idZ the value for tyg_user_list.id_z
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setIdZ(String idZ) {
            this.idZ = idZ;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.id_f
         *
         * @return the value of tyg_user_list.id_f
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public String getIdF() {
            return idF;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.id_f
         *
         * @param idF the value for tyg_user_list.id_f
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setIdF(String idF) {
            this.idF = idF;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.id_no
         *
         * @return the value of tyg_user_list.id_no
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public String getIdNo() {
            return idNo;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.id_no
         *
         * @param idNo the value for tyg_user_list.id_no
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setIdNo(String idNo) {
            this.idNo = idNo;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.check_pass_time
         *
         * @return the value of tyg_user_list.check_pass_time
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Long getCheckPassTime() {
            return checkPassTime;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.check_pass_time
         *
         * @param checkPassTime the value for tyg_user_list.check_pass_time
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setCheckPassTime(Long checkPassTime) {
            this.checkPassTime = checkPassTime;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.check_status
         *
         * @return the value of tyg_user_list.check_status
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Byte getCheckStatus() {
            return checkStatus;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.check_status
         *
         * @param checkStatus the value for tyg_user_list.check_status
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setCheckStatus(Byte checkStatus) {
            this.checkStatus = checkStatus;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.auditor_id
         *
         * @return the value of tyg_user_list.auditor_id
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Integer getAuditorId() {
            return auditorId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.auditor_id
         *
         * @param auditorId the value for tyg_user_list.auditor_id
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setAuditorId(Integer auditorId) {
            this.auditorId = auditorId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.phone
         *
         * @return the value of tyg_user_list.phone
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Long getPhone() {
            return phone;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.phone
         *
         * @param phone the value for tyg_user_list.phone
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setPhone(Long phone) {
            this.phone = phone;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.referrer_identity
         *
         * @return the value of tyg_user_list.referrer_identity
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Byte getReferrerIdentity() {
            return referrerIdentity;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.referrer_identity
         *
         * @param referrerIdentity the value for tyg_user_list.referrer_identity
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setReferrerIdentity(Byte referrerIdentity) {
            this.referrerIdentity = referrerIdentity;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.real_name
         *
         * @return the value of tyg_user_list.real_name
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public String getRealName() {
            return realName;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.real_name
         *
         * @param realName the value for tyg_user_list.real_name
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setRealName(String realName) {
            this.realName = realName;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.consume_sum
         *
         * @return the value of tyg_user_list.consume_sum
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public BigDecimal getConsumeSum() {
            return consumeSum;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.consume_sum
         *
         * @param consumeSum the value for tyg_user_list.consume_sum
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setConsumeSum(BigDecimal consumeSum) {
            this.consumeSum = consumeSum;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.sum_consum_ticket
         *
         * @return the value of tyg_user_list.sum_consum_ticket
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public BigDecimal getSumConsumTicket() {
            return sumConsumTicket;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.sum_consum_ticket
         *
         * @param sumConsumTicket the value for tyg_user_list.sum_consum_ticket
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setSumConsumTicket(BigDecimal sumConsumTicket) {
            this.sumConsumTicket = sumConsumTicket;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.enough_fans_v0
         *
         * @return the value of tyg_user_list.enough_fans_v0
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Byte getEnoughFansV0() {
            return enoughFansV0;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.enough_fans_v0
         *
         * @param enoughFansV0 the value for tyg_user_list.enough_fans_v0
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setEnoughFansV0(Byte enoughFansV0) {
            this.enoughFansV0 = enoughFansV0;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.f_id
         *
         * @return the value of tyg_user_list.f_id
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public Long getfId() {
            return fId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.f_id
         *
         * @param fId the value for tyg_user_list.f_id
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setfId(Long fId) {
            this.fId = fId;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method returns the value of the database column tyg_user_list.check_detail
         *
         * @return the value of tyg_user_list.check_detail
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public String getCheckDetail() {
            return checkDetail;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column tyg_user_list.check_detail
         *
         * @param checkDetail the value for tyg_user_list.check_detail
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        public void setCheckDetail(String checkDetail) {
            this.checkDetail = checkDetail;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tyg_user_list
         *
         * @mbggenerated Thu Mar 15 21:44:03 CST 2018
         */
        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append(getClass().getSimpleName());
            sb.append(" [");
            sb.append("Hash = ").append(hashCode());
            sb.append(", userId=").append(userId);
            sb.append(", userOrShop=").append(userOrShop);
            sb.append(", parentUserId=").append(parentUserId);
            sb.append(", userPwd=").append(userPwd);
            sb.append(", nickName=").append(nickName);
            sb.append(", logo=").append(logo);
            sb.append(", gender=").append(gender);
            sb.append(", userQrcode=").append(userQrcode);
            sb.append(", registerTime=").append(registerTime);
            sb.append(", paypwd=").append(paypwd);
            sb.append(", authentication=").append(authentication);
            sb.append(", authenticateTime=").append(authenticateTime);
            sb.append(", createTime=").append(createTime);
            sb.append(", cutOff=").append(cutOff);
            sb.append(", cutOffTime=").append(cutOffTime);
            sb.append(", userLevel=").append(userLevel);
            sb.append(", userRoot=").append(userRoot);
            sb.append(", idZ=").append(idZ);
            sb.append(", idF=").append(idF);
            sb.append(", idNo=").append(idNo);
            sb.append(", checkPassTime=").append(checkPassTime);
            sb.append(", checkStatus=").append(checkStatus);
            sb.append(", auditorId=").append(auditorId);
            sb.append(", phone=").append(phone);
            sb.append(", referrerIdentity=").append(referrerIdentity);
            sb.append(", realName=").append(realName);
            sb.append(", consumeSum=").append(consumeSum);
            sb.append(", sumConsumTicket=").append(sumConsumTicket);
            sb.append(", enoughFansV0=").append(enoughFansV0);
            sb.append(", fId=").append(fId);
            sb.append(", checkDetail=").append(checkDetail);
            sb.append(", serialVersionUID=").append(serialVersionUID);
            sb.append("]");
            return sb.toString();
        }
    }
}
